services:
#    polytech_ecommerce.example:
#        class: Polytech\EcommerceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    setNewReference:
        class: Polytech\EcommerceBundle\Services\GetReference
        arguments: [@security.context, @doctrine.orm.entity_manager]

    tva:
      class: Polytech\EcommerceBundle\Twig\Extension\TvaExtension
      tags:
        - { name: twig.extension }

    montantTva:
      class: Polytech\EcommerceBundle\Twig\Extension\MontantTvaExtension
      tags:
        - { name: twig.extension }
        
    redirectionListener:
      class: Polytech\EcommerceBundle\Listener\RedirectionListener
      arguments: [@service_container,@session]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        
