<?php

namespace Polytech\GestionFichiersBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * FichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierRepository extends EntityRepository
{
    /*
	public function myFindAll($Entreprise){
        $qb = $this->createQueryBuilder('f');

        // On fera la jointure avec les entreprises
        $qb
          ->addSelect('e')
          ->join('f.entreprise', 'e')      
        ;	

        // Enfin, on retourne le résultat sous forme de tableau
        return $qb
          ->getQuery()
          ->getResult()
        ;
	}*/
    
    public function myFindAll($entreprise)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.entreprise = :entreprise')
                ->orderBy('u.id')
                ->setParameter('entreprise', $entreprise);
        
        return $qb->getQuery()->getResult();
    }
}
