<?php

namespace Polytech\DronesBundle\Entity;

/**
 * DronesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DronesRepository extends \Doctrine\ORM\EntityRepository
{
    public function byEntreprise($entreprise)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.entreprise = :entreprise')
                ->orderBy('u.id')
                ->setParameter('entreprise', $entreprise);
        
        return $qb->getQuery()->getResult();
    }
}
