<?php

namespace Polytech\EcommerceBundle\Entity;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
    public function byFacture($entreprise)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.entreprise = :entreprise')
                ->andWhere('u.valider > 0')
                ->andWhere('u.reference != 0')
                ->orderBy('u.id')
                ->setParameter('entreprise', $entreprise);
        
        return $qb->getQuery()->getResult();
    }
}
